# -*- coding: utf-8 -*-
"""Belajar Analisis Data dengan Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2VmQHlKmpVhGTIlDNE35XQMjmYmi_4e

# Proyek Analisis Data: Bike-sharing-dataset
- **Nama : Ilham Oktavian**
- **Email : ilhamoktavian74@gmail.com**
- **ID Dicoding : ilham_oktavian_74**

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : Berapa total terpinjam pada bulan Desember 2012?
- Pertanyaan 2 : Bagaimana kinerja peminjaman dalam setahun terakhir?

### Connect to Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Import Semua Packages/Library yang Digunakan"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""## Data Wrangling

### Gathering Data
"""

url = './drive/MyDrive/Dataset/day.csv'
day = pd.read_csv(url)
day

url2 = './drive/MyDrive/Dataset/hour.csv'
hour = pd.read_csv(url2)
hour

q = hour.groupby('dteday')['cnt'].sum().reset_index()
q

"""### Assessing Data"""

hour.info()



"""Perbedaan dataset day dan hour adalah dataset day adalah akumulasi dari dataset hour. Berikut merupakan penjelasan tiap kolom:
* instant: indeks
* dteday : tanggal peminjaman sepeda
* season : musim ketika peminjaman sepeda dilakukan. Musim dingin (1), musim semi (2), musim panas (3), musim gugur (4)
* yr : tahun. 2011 (0), 2012 (1)
* mnth : bulan, 1 sampai 12
* hr : jam, 1 hari 24 jam (0 hingga 23)
* holiday :  indikator yang menunjukkan apakah hari itu merupakan hari libur atau tidak
* weekday : hari dalam seminggu
* workingday : indikator yang jika hari tersebut bukan akhir pekan atau hari libur maka nilainya 1, jika tidak maka nilainya 0
* weathersit : kondisi cuaca pada saat peminjaman sepeda dilakukan. Cerah (1), Mendung (2), Hujan atau salju ringan (3), Hujan Lebat (4)
* temp :   suhu dalam derajat Celsius pada saat peminjaman sepeda dilakukan
* atemp: suhu yang dirasakan dalam derajat Celsius pada saat peminjaman sepeda dilakukan
* hum: Kelembapan
* windspeed: Kecepatan angin
* casual: jumlah peminjam sepeda biasa, yang tidak  berlangganan tetap
* registered: jumlah peminjam sepeda yang terdaftar member
* cnt: total jumlah peminjam sepeda, yaitu gabungan dari jumlah peminjam casual dan peminjam terdaftar
"""

print("Jumlah entri untuk setiap kolom dalam data hour:")
hour.nunique()

hour.isna().sum()

"""tidak ada missing values dalam setiap kolom"""

hour.duplicated().sum()

"""tidak ada data yang duplikat"""

hour.describe()

"""### Cleaning Data

**outliers**
"""

Q1 = (hour['cnt']).quantile(0.25)
Q3 = (hour['cnt']).quantile(0.75)
IQR = Q3 - Q1

maximum = Q3 + (1.5*IQR)
minimum = Q1 - (1.5*IQR)

kondisi_lower_than = hour['cnt'] < minimum
kondisi_more_than = hour['cnt'] > maximum

print(kondisi_lower_than.sum() + kondisi_more_than.sum())

"""karena jumlah outlier hanya sedikit jadi bisa langsung didrop"""

hour.drop(hour[kondisi_lower_than].index, inplace=True)
hour.drop(hour[kondisi_more_than].index, inplace=True)
hour

"""**Memperbaiki tipe data**"""

hour['dteday'] = pd.to_datetime(hour['dteday'])

hour.info()

"""## Exploratory Data Analysis (EDA)"""

bulanan = hour.groupby(pd.Grouper(key='dteday', freq='M')).sum()
plt.figure(figsize=(10, 3))
plt.plot(bulanan.index, bulanan['cnt'],marker='o',linestyle='-')
plt.title('Jumlah Penyewaan Sepeda per Bulan (Jan 2011 - Des 2012)')
plt.xlabel('Bulan')
plt.ylabel('Jumlah Penyewaan')
plt.grid(True)
plt.show()

fitur = ['mnth', 'hr', 'weekday', 'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered']
for feature in fitur:
    fig = px.histogram(hour, x=feature, y='cnt', title=f'Distribusi {feature}')
    fig.update_traces(marker_line_color='black', marker_line_width=1)
    fig.update_layout(yaxis_title='Jumlah peminjam')
    fig.show()

w = ['yr', 'holiday', 'workingday', 'weathersit']

for w in w:
    fig = px.pie(hour, names=w, values='cnt',
                 title=f'Distribusi Jumlah Penyewaan Berdasarkan {w}')
    fig.show()

matrikskorelasi = hour.corr()
plt.figure(figsize=(9,6))
sns.heatmap(matrikskorelasi, annot=True, annot_kws={"size": 6})
plt.title('Korelasi Antar Kolom')
plt.show()

"""## Visualization & Explanatory Analysis

### Pertanyaan 1: Berapa total terpinjam pada bulan Desember 2012?
"""

total = hour[(hour['yr'] == 1) & (hour['mnth'] == 12)]['cnt'].sum()

print("Total terpinjam pada bulan Desember 2012:", total)

"""### Pertanyaan 2: Bagaimana kinerja peminjaman dalam setahun terakhir?"""

data = hour[hour['yr'] == 1]
bulan = data.groupby(pd.Grouper(key='dteday', freq='M')).sum()
plt.figure(figsize=(10, 3))
plt.plot(bulan.index, bulan['cnt'], marker='o', linestyle='-')
plt.xticks(bulan.index, bulan.index.strftime('%b'))
plt.title('Kinerja peminjaman dalam setahun terakhir')
plt.xlabel('Bulan')
plt.ylabel('Jumlah Penyewaan')
plt.grid(True)
plt.show()

"""## Conclusion

- Conclution pertanyaan 1: Total sepeda terpinjam pada bulan Desember 2012 yaitu 114.538
- Conclution pertanyaan 2: dari bulan januari hingga mei peminjaman sepeda terus meningkat, sempat turun sedikit pada bulan juni, namun naik kembali pada bulan juli (pada bulan ini tercapai peminjaman terbanyak pada tahun 2012), namun setelah bulan juli jumlah peminjaman sepeda mengalami penurunan hingga akhir tahun 2012
- Berdasarkan matriks korelasi didapatkan faktor yang paling berpengaruh yaitu jam peminjaman. Dan berdasarkan distribusinya, sepeda paling sering dipinjam pada pukul 4 sore hingga 7 malam
- Selain jam, suhu juga sangat berpengaruh pada minat meminjam. Suhu yang dirasa nyaman untuk bersepeda yakni pada suhu 0.6 hingga 0.7 Celsius
"""

